version: "3"
services:
  redis:
    build: ./Redis
    networks:
      - project_network
    ports:
      - "6379:6379"  
  service1:
    build: ./Service_1
    links:
      - redis
    networks:
      - project_network
    ports:
      - "8080:8080"
networks:
  project_network: